import express from 'express';
import { signup, verifyOTP, resendOTP, login, getMe, forgotPassword, resetPassword } from '../controllers/auth.controller.js';
import { protect } from '../middleware/auth.js';
const router = express.Router();
router.post('/signup',          signup);
router.post('/verify-otp',      verifyOTP);
router.post('/resend-otp',      resendOTP);
router.post('/login',           login);
router.post('/forgot-password', forgotPassword);
router.post('/reset-password',  resetPassword);
router.get('/me',               protect, getMe);
export default router;
